server:
  port: 50000
  servlet:
    context-path: /order

spring:
  application:
    name: sca-module-order
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
        username: nacos
        password: nacos
        namespace: dev
        group: sca